### ISSUE TITLE
Hands on cats?

### ISSUE THREAD

**Issue by loicdescotte** [YannMoisan/hands-on-scalaz#1]
Great repo, great idea, thanks for your work!
Is there any plan to do the same for cats?

**Comment by YannMoisan** [comment]
I've already thought about that. It's the next step.
Thanks for your feedback !

**Comment by loicdescotte** [comment]
Great to hear!

Le mer. 15 juin 2016 à 14:34, Yann Moisan <notifications@github.com> a
écrit :
